# MSP magic bytes and protocol identifiers
MSP_PREAMBLE_V1 = b'$M'
MSP_PREAMBLE_V2 = b'$X'
MSP_DIRECTION_TO_FC = ord('<')
MSP_DIRECTION_FROM_FC = ord('>')
MSP_DIRECTION_ERROR = ord('!')

MSP_V1_OVERHEAD = 6  # preamble(2) + dir(1) + len(1) + code(1) + checksum(1)
MSP_V2_OVERHEAD = 9  # preamble(2) + dir(1) + flag(1) + code(2) + len(2) + checksum(1)

# MSP command codes
MSP_API_VERSION = 1
MSP_FC_VARIANT = 2
MSP_FC_VERSION = 3
MSP_BOARD_INFO = 4
MSP_BUILD_INFO = 5
MSP_UID = 160

MSP_BLACKBOX_CONFIG = 80

MSP_DATAFLASH_SUMMARY = 70
MSP_DATAFLASH_READ = 71
MSP_DATAFLASH_ERASE = 72

# Blackbox device types
BLACKBOX_DEVICE_NONE = 0
BLACKBOX_DEVICE_FLASH = 1
BLACKBOX_DEVICE_SDCARD = 2
BLACKBOX_DEVICE_SERIAL = 3

# DATAFLASH_SUMMARY flags
DATAFLASH_FLAG_SUPPORTED = 0x01
DATAFLASH_FLAG_READY = 0x02

# Compression types in DATAFLASH_READ response
DATAFLASH_COMPRESSION_NONE = 0
DATAFLASH_COMPRESSION_HUFFMAN = 1

# Expected FC variant
BTFL_VARIANT = b'BTFL'
